### ISSUE TITLE
Question: how to use this library with changes from Github (unreleased changes)?

### ISSUE THREAD

**Issue by antonioorct** [taozhi8833998/node-sql-parser#1842]
There is a PR (#1794) that I need to use right now that's in the `master` branch but not released yet on npm.

I've tried to add the dependency directly from Github: `pnpm add https://github.com/taozhi8833998/node-sql-parser#master` but that failed due to the module not being transpiled.

Is there any other way or suggestion to work around this?

**Comment by taozhi8833998** [comment]
@antonioorct new version `5.0.0` has been released, please check it.

**Comment by antonioorct** [comment]
It works, thanks!

It would still be useful to know how to use an unpublished version though

**Comment by taozhi8833998** [comment]
> It works, thanks!
> 
> It would still be useful to know how to use an unpublished version though

I will add the sop later.

**Comment by karanssj4** [comment]
@antonioorct I've needed to the same in the past.
You cant use this repo as a package source because it doesn't contain the compiled peg parsers. Those are generated by the build scripts in package.json

you'll need to clone the repo and built it yourself and then the built artifacts can be used in your code.

@taozhi8833998 can correct me if I'm wrong

**Comment by taozhi8833998** [comment]
@antonioorct You can try it.
