### ISSUE TITLE
npm package size is too big?

### ISSUE THREAD

**Issue by haoliangyu** [taozhi8833998/node-sql-parser#501]
![image](https://user-images.githubusercontent.com/1726265/98829984-d8774c00-2407-11eb-9959-5015d9436dc0.png)

As the screenshot shows, the unpacked size is 31.2MB. This is an unusual size for a node package and is there a reason for it?

**Comment by oguimbal** [comment]
Yes, there are multiple builds inside:
- One per language x module system (which is about (10 x 2 x 100kB per language)
- One global build which supports all languages (~800kB)

Add the sourcemaps, and you get to 30MB.

All those builds are here precisely because including a single build is quite overkill (~800kB) when you only use one language. This allows you to choose the right build for you.

**Comment by haoliangyu** [comment]
Makes sense. Thank you for the explaination.
